<?php
//-1 refers to a vulnerability that does not require a taint, 0 refers to all parameters, 1 refers to the first parameter, and 2 refers to the second parameter 999 refers to removing the first parameter, 998 refers to removing the first and second parameters ..；

$XSSRISKFUNCLIST = array(
    'XSS' => [[0], []],
    'print_r' =>[[1],[]],
    'printf'  => [[1,2], []],
    'vprintf' => [[2], []],
    'var_dump' => [[0], []],
    'debug_zval_dump' => [[0], []],
);

$XSSRISKCLASSFUNCLIST = array(
    'Exception' => ['getMessage'=>[1001,[]]],
);

$ERRORSETFUNCLIST = array(
    'trigger_error' => [[1], []],
    'user_error' => [[1], []],
);

$ERRORGETFUNCLIST = array(
    'error_get_last' => [[-1],[]],
);

$SQLRISKFUNCLIST = array(
    'SQLI' => [[0], []],
    'odbc_exec' => [[2],[]],
    'mysqli_query' => [[2],[]],
    'mysql_query' => [[1],[]],
);

$DIYLFUNCLIST = array(
    'create_function' => [[-1],"CE"],
);

$OBFUNCLIST = array(
    'ob_start',
    'ob_flush',
    'ob_clean',
    'ob_end_flush',
    'ob_end_clean',
    'ob_get_flush',
    'ob_get_clean',
    'ob_get_contents',
);

$FILESYSFUNCLIST = array(
    'set_include_path',
    'get_include_path',
    'define',
    'chdir',
    'dirname',
    'basename',
);

$CERISKFUNCLIST = array(
    'CE' => [[-1],[]],  
    'POSSIBLE_CE' => [[-1],[]],  
    'preg_replace' => [[2],[]],             
    'preg_filter' => [[2],[]], 
    'preg_replace_callback' => [[2],[]], 
    'preg_replace_callback_array' => [[2],[]], 
    'preg_split' => [[2],[]], 
    'preg_quote' => [[2],[]], 
    'preg_grep' => [[2],[]], 
    'preg_last_error' => [[2],[]], 
    'preg_last_error_msg' => [[2],[]], 
    'mb_ereg_match' => [[2],[]], 
    'mb_ereg_replace_callback' => [[2],[]], 
    'mb_ereg_replace' => [[2],[]], 
    'mb_ereg_search_pos' => [[2],[]], 
    'mb_ereg_search_regs' => [[2],[]], 
    'mb_ereg_search' => [[2],[]], 
    'mb_eregi' => [[2],[]],              
    'mb_eregi_replace' => [[2],[]],      
    'mb_split' => [[2],[]], 
    'mb_ereg_search_init' => [[1],[]], 
    'mb_ereg' => [[1],[]],       
    // callable        
    'call_user_func' => [[0],[]],            
    'call_user_func_array' => [[0],[]], 
    'forward_static_call' => [[0],[]], 
    'forward_static_call_array' => [[0],[]], 
    'register_shutdown_function' => [[0],[]], 
    'register_tick_function' => [[0],[]],
    'array_walk' => [[0], []],                       // array_walk($_GET['a'],$_GET['b']);  a[]=whoami&b=system
    'array_map' => [[0], []],                        // array_map($_GET['a'],$_GET['b']);    xxx.php?a=system&b[]=whoami
    'array_filter' => [[0], []],                     // array_filter(array($_GET['cmd']),$_GET['func']);   ?func=system&cmd=whoami
    'usort' => [[0], []],                            // usort(...$_GET);   xxx.php?1[]=test&1[]=phpinfo();&2=assert
    'iterator_apply' => [[0], []],                  
    'uasort' => [[0], []],
    'uksort' => [[0], []],
    'array_walk_recursive' => [[0], []],
    'array_intersect_ukey' => [[0], []],            
    'array_uintersect' => [[0], []],                
    'array_uintersect_assoc' => [[0], []],          
    'array_uintersect_uassoc' => [[0], []],         
    'array_diff_ukey' => [[0], []],                 
    'array_udiff' => [[0], []],                     
    'array_diff_uassoc' => [[0], []],               
    'array_udiff_assoc' => [[0], []],               
    'array_udiff_uassoc' => [[0], []],              
    'array_reduce' => [[1], []],                    
    // classic
    'assert' => [[1], []],                           
    'exec' => [[1], []],
    'system' => [[1], []],
    'passthru' => [[1], []],
    'shell_exec' => [[1], []],
    'popen' => [[1], []],                            // $test = "whoami";  $fp = popen($test,"r");  
    'proc_open' => [[1], []],                        // $fp = proc_open('whoami', [STDIN, STDOUT, STDOUT], $pipes);  proc_close($fp);

);


$FIRISKFUNCLIST = array(
    'FI' => [[-1], []],
    'spl_autoload' => [],
    'spl_autoload_call' => [],
    'spl_autoload_extensions' => [],
    'spl_autoload_functions' => [],
    'spl_autoload_register' => [[1], []],
);

$FDELRISKFUNCLIST = array(
    'AFD' => [[0], []],
    'unlink' => [[1], []],
);

$FURISKFUNCLIST = array(
    'UFU' => [[0], []],
    'move_uploaded_file' => [[1,2], []],
    'file_put_contents' => [[2], []],
    'fprintf' => [[998], []],       
    'vfprintf' => [[998], []],      
);

$INFOLEAKFUNCLIST = array(
    'SDE' => [[-1], []],
    'highlight_file' => [[1], []],
    'highlight_string' => [[1], []],
    'show_source' => [[1], []],
    'php_strip_whitespace' => [[1], []],
    'phpinfo' => [[-1], []],
    'file_get_contents' => [[1], []],
    //SSRF
    'fsockopen' => [[1], []],               
    'pfsockopen' => [[1], []],
    'curl_setopt' => [[3], []],
    'fopen' => [[1], []],
    'readfile' => [[1], []],
);

$SETCOOKIEFUNCLIST = array(
    'setrawcookie',
    'setcookie',
);

$SAFEFUNCLIST = array(
    'zend_version',
    'strlen',
    'strcmp',
    'strncmp',
    'strcasecmp',
    'strncasecmp',
    'error_reporting',
    'defined',
    'get_class',
    'get_called_class',
    'get_parent_class',
    'is_subclass_of',
    'is_a',
    'get_class_vars',
    'get_class_methods',
    'method_exists',
    'property_exists',
    'class_exists',
    'interface_exists',
    'trait_exists',
    'function_exists',
    'class_alias',          
    'get_included_files',
    'get_required_files',
    'user_error',
    'set_error_handler',
    'restore_error_handler',
    'set_exception_handler',
    'restore_exception_handler',
    'get_declared_classes',
    'get_declared_traits',
    'get_declared_interfaces',
    'get_defined_functions',
    'get_defined_vars',
    'get_resource_type',
    'get_resource_id',
    'get_resources',
    'get_loaded_extensions',
    'get_defined_constants',
    'debug_backtrace',
    'debug_print_backtrace',
    'extension_loaded',
    'get_extension_funcs',
    'gc_mem_caches',
    'gc_collect_cycles',
    'gc_enabled',
    'gc_enable',
    'gc_disable',
    'gc_status',
    'bcadd',
    'bcsub',
    'bcmul',
    'bcdiv',
    'bcmod',
    'bcpowmod',
    'bcpow',
    'bcsqrt',
    'bccomp',
    'bcscale',
    'cal_days_in_month',
    'cal_from_jd',
    'cal_info',
    'cal_to_jd',
    'easter_date',
    'easter_days',
    'frenchtojd',
    'gregoriantojd',
    'jddayofweek',
    'jdmonthname',
    'jdtofrench',
    'jdtogregorian',
    'jdtojewish',
    'jdtojulian',
    'jdtounix',
    'jewishtojd',
    'juliantojd',
    'unixtojd',
    'ctype_alnum',          
    'ctype_alpha',
    'ctype_cntrl',
    'ctype_digit',
    'ctype_lower',
    'ctype_graph',
    'ctype_print',
    'ctype_punct',
    'ctype_space',
    'ctype_upper',
    'ctype_xdigit',
    'strtotime',
    'date',
    'idate',
    'gmdate',
    'mktime',
    'gmmktime',
    'checkdate',
    'strftime',
    'gmstrftime',
    'time',
    'localtime',
    'getdate',
    'date_create',
    'date_create_immutable',
    'date_create_from_format',
    'date_create_immutable_from_format',
    'date_parse',
    'date_parse_from_format',
    'date_get_last_errors',
    'date_format',
    'date_modify',
    'date_add',
    'date_sub',
    'date_timezone_get',
    'date_timezone_set',
    'date_offset_get',
    'date_diff',
    'date_time_set',
    'date_date_set',
    'date_isodate_set',
    'date_timestamp_set',
    'date_timestamp_get',
    'timezone_open',
    'timezone_name_get',
    'timezone_name_from_abbr',
    'timezone_offset_get',
    'timezone_transitions_get',
    'timezone_location_get',
    'timezone_identifiers_list',
    'timezone_abbreviations_list',
    'timezone_version_get',
    'date_interval_create_from_date_string',
    'date_interval_format',
    'date_default_timezone_set',
    'date_default_timezone_get',
    'date_sunrise',
    'date_sunset',
    'date_sun_info',
    'filter_has_var',
    'filter_input',
    'filter_var',
    'filter_input_array',
    'filter_var_array',
    'filter_list',
    'filter_id',
    'hash',
    'hash_file',
    'hash_hmac',
    'hash_hmac_file',
    'hash_init',
    'hash_update',
    'hash_update_stream',
    'hash_update_file',
    'hash_final',
    'hash_copy',
    'hash_algos',
    'hash_hmac_algos',
    'hash_pbkdf2',
    'hash_equals',
    'hash_hkdf',
    'mhash_get_block_size',
    'mhash_get_hash_name',
    'mhash_keygen_s2k',
    'mhash_count',
    'mhash',
    'iconv_strlen',
    'iconv_substr',
    'iconv_strpos',
    'iconv_strrpos',
    'iconv',
    'iconv_set_encoding',
    'iconv_get_encoding',
    'json_last_error',
    'json_last_error_msg',
    'readline_info',
    'readline_add_history',
    'readline_clear_history',
    'readline_list_history',
    'readline_write_history',
    'readline_completion_function',
    'session_name',
    'session_module_name',
    'session_save_path',
    'session_id',
    'session_create_id',
    'session_regenerate_id',
    'session_decode',
    'session_encode',
    'session_destroy',
    'session_unset',
    'session_gc',
    'session_get_cookie_params',
    'session_write_close',
    'session_abort',
    'session_reset',
    'session_status',
    'session_register_shutdown',
    'session_commit',
    'session_set_save_handler',
    'session_cache_limiter',
    'session_cache_expire',
    'session_set_cookie_params',
    'session_start',
    'class_implements',
    'class_parents',
    'class_uses',
    'spl_autoload_unregister',
    'spl_classes',                  
    'spl_object_hash',
    'spl_object_id',
    'iterator_count',
    'set_time_limit',
    'header_register_callback',
    'ob_get_level',
    'ob_get_length',
    'ob_list_handlers',
    'ob_get_status',
    'ob_implicit_flush',
    'output_reset_rewrite_vars',
    'output_add_rewrite_var',
    'stream_wrapper_register',      
    'stream_register_wrapper',
    'stream_wrapper_unregister',
    'stream_wrapper_restore',
    'count',
    'sizeof',
    'min',
    'max',
    'range',
    'constant',
    'ip2long',
    'long2ip',
    'getenv',
    'putenv',
    'getopt',
    'flush',
    'sleep',
    'usleep',
    'time_nanosleep',
    'time_sleep_until',
    'get_current_user',
    'get_cfg_var',
    'error_log',
    'error_clear_last',
    'ini_get',
    'ini_get_all',
    'ini_set',
    'ini_alter',
    'ini_restore',
    'connection_aborted',
    'connection_status',
    'ignore_user_abort',
    'getservbyname',
    'getservbyport',
    'getprotobyname',
    'getprotobynumber',
    'unregister_tick_function',
    'is_uploaded_file',
    'parse_ini_file',       
    'parse_ini_string',
    'get_browser',
    'crc32',
    'crypt',                    
    'gethostname',
    'gethostbyaddr',
    'gethostbyname',
    'gethostbynamel',
    'dns_check_record',
    'checkdnsrr',
    'dns_get_record',
    'dns_get_mx',
    'getmxrr',
    'net_get_interfaces',
    'ftok',
    'hrtime',
    'lcg_value',
    'md5',                    
    'md5_file',               
    'getmyuid',
    'getmygid',
    'getmypid',
    'getmyinode',
    'getlastmod',
    'sha1',                   
    'sha1_file',              
    'openlog',
    'closelog',
    'syslog',
    'inet_ntop',
    'inet_pton',
    'metaphone',
    'header',
    'header_remove',
    'http_response_code',
    'headers_sent',
    'headers_list',
    'get_html_translation_table',
    'assert_options',
    'strspn',
    'strcspn',
    'strcoll',
    'chop',
    'strtok',
    'pathinfo',
    'strpos',
    'stripos',
    'strrpos',
    'strripos',
    'str_contains',
    'str_starts_with',
    'str_ends_with',
    'quotemeta',
    'similar_text',
    'hebrev',
    'nl2br',
    'setlocale',
    'str_getcsv',
    'str_repeat',
    'count_chars',
    'strnatcmp',
    'localeconv',
    'strnatcasecmp',
    'substr_count',
    'sscanf',
    'str_shuffle',
    'str_word_count',
    'str_split',
    'strpbrk',                              
    'substr_compare',
    'utf8_encode',
    'utf8_decode',
    'opendir',
    'dir',
    'closedir',
    'getcwd',
    'rewinddir',
    'readdir',
    'scandir',
    'glob',
    'escapeshellcmd',              
    'escapeshellarg',              
    'proc_nice',
    'flock',
    'get_meta_tags',
    'pclose',
    'rewind',
    'rmdir',
    'umask',
    'fclose',
    'feof',
    'fgetc',
    'fgets',
    'fread',
    'fscanf',
    'fpassthru',
    'ftruncate',
    'fstat',
    'fseek',
    'ftell',
    'fflush',
    'fwrite',
    'fputs',
    'mkdir',
    'rename',
    'copy',
    'tempnam',
    'tmpfile',
    'file',
    'fputcsv',
    'fgetcsv',
    'realpath',
    'fnmatch',
    'sys_get_temp_dir',
    'fileatime',
    'filectime',
    'filegroup',
    'fileinode',
    'filemtime',
    'fileowner',
    'fileperms',
    'filesize',
    'filetype',
    'file_exists',
    'is_writable',
    'is_writeable',
    'is_readable',
    'is_executable',
    'is_file',
    'is_dir',
    'is_link',
    'stat',
    'lstat',
    'chown',
    'chgrp',
    'chmod',
    'touch',
    'clearstatcache',
    'disk_total_space',
    'disk_free_space',
    'diskfreespace',
    'realpath_cache_get',
    'realpath_cache_size',
    'http_build_query',
    'image_type_to_mime_type',
    'image_type_to_extension',
    'getimagesize',
    'getimagesizefromstring',
    'phpversion',
    'phpcredits',
    'php_sapi_name',
    'php_uname',
    'php_ini_scanned_files',
    'php_ini_loaded_file',
    'iptcembed',
    'iptcparse',
    'levenshtein',
    'readlink',
    'linkinfo',
    'symlink',
    'link',
    'mail',
    'abs',
    'ceil',
    'floor',
    'round',
    'sin',
    'cos',
    'tan',
    'asin',
    'acos',
    'atan',
    'atanh',
    'atan2',
    'sinh',
    'cosh',
    'tanh',
    'asinh',
    'acosh',
    'expm1',
    'log1p',
    'pi',
    'is_finite',
    'is_nan',
    'intdiv',
    'is_infinite',
    'pow',
    'exp',
    'log',
    'log10',
    'sqrt',
    'hypot',
    'deg2rad',
    'rad2deg',
    'bindec',
    'hexdec',
    'octdec',
    'decbin',
    'decoct',
    'dechex',
    'base_convert',
    'number_format',
    'fmod',
    'fdiv',
    'microtime',
    'gettimeofday',
    'getrusage',
    'password_get_info',
    'password_hash',
    'password_needs_rehash',
    'password_verify',
    'password_algos',
    'proc_close',
    'proc_terminate',
    'proc_get_status',
    'quoted_printable_decode',
    'quoted_printable_encode',
    'mt_srand',
    'srand',
    'rand',
    'mt_rand',
    'mt_getrandmax',
    'getrandmax',
    'random_bytes',
    'random_int',
    'soundex',
    'stream_select',
    'stream_context_create',
    'stream_context_set_params',
    'stream_context_get_params',
    'stream_context_set_option',
    'stream_context_get_options',
    'stream_context_get_default',
    'stream_context_set_default',
    'stream_filter_prepend',
    'stream_filter_append',
    'stream_filter_remove',
    'stream_socket_client',
    'stream_socket_server',
    'stream_socket_accept',
    'stream_socket_get_name',
    'stream_socket_recvfrom',
    'stream_socket_sendto',
    'stream_socket_enable_crypto',
    'stream_socket_shutdown',
    'stream_socket_pair',
    'stream_copy_to_stream',
    'stream_get_contents',
    'stream_supports_lock',
    'stream_set_write_buffer',
    'set_file_buffer',
    'stream_set_read_buffer',
    'stream_set_blocking',
    'socket_set_blocking',
    'stream_get_meta_data',
    'socket_get_status',
    'stream_get_line',
    'stream_resolve_include_path',
    'stream_get_wrappers',
    'stream_get_transports',
    'stream_is_local',
    'stream_isatty',
    'sapi_windows_vt100_support',
    'stream_set_chunk_size',
    'stream_set_timeout',
    'socket_set_timeout',
    'gettype',
    'get_debug_type',
    'settype',
    'intval',
    'floatval',
    'doubleval',
    'boolval',
    'strval',
    'is_null',
    'is_resource',
    'is_bool',
    'is_int',
    'is_integer',
    'is_long',
    'is_float',
    'is_double',
    'is_numeric',
    'is_string',
    'is_array',
    'is_object',
    'is_scalar',
    'is_callable',
    'is_iterable',
    'is_countable',
    'uniqid',
    'parse_url',
    'urlencode',
    'urldecode',
    'rawurlencode',
    'rawurldecode',
    'get_headers',
    'stream_bucket_make_writeable',
    'stream_bucket_prepend',
    'stream_bucket_append',
    'stream_bucket_new',
    'stream_get_filters',
    'stream_filter_register',
    'var_export',
    'memory_get_usage',
    'memory_get_peak_usage',
    'version_compare',
    'sapi_windows_cp_set',
    'sapi_windows_cp_get',
    'sapi_windows_cp_conv',
    'sapi_windows_cp_is_utf8',
    'sapi_windows_set_ctrl_handler',
    'sapi_windows_generate_ctrl_event',
    'token_get_all',
    'token_name',
    'zip_open',
    'zip_close',
    'zip_read',
    'zip_entry_open',
    'zip_entry_close',
    'zip_entry_read',
    'zip_entry_name',
    'zip_entry_compressedsize',
    'zip_entry_filesize',
    'zip_entry_compressionmethod',
    'ob_gzhandler',
    'zlib_get_coding_type',
    'gzfile',
    'gzopen',
    'readgzfile',
    'gzwrite',
    'gzputs',
    'gzrewind',
    'gzclose',
    'gzeof',
    'gzgetc',
    'gzpassthru',
    'gzseek',
    'gztell',
    'gzread',
    'gzgets',
    'deflate_init',
    'inflate_init',
    'inflate_get_status',
    'inflate_get_read_len',
    'libxml_set_streams_context',
    'libxml_use_internal_errors',
    'libxml_get_last_error',
    'libxml_get_errors',
    'libxml_clear_errors',
    'libxml_disable_entity_loader',
    'libxml_set_external_entity_loader',
    'dom_import_simplexml',
    'pdo_drivers',
    'simplexml_load_file',
    'simplexml_load_string',
    'simplexml_import_dom',
    'xml_parser_create',                            
    'xml_parser_create_ns',
    'xml_set_object',
    'xml_set_element_handler',
    'xml_set_character_data_handler',
    'xml_set_processing_instruction_handler',
    'xml_set_default_handler',
    'xml_set_unparsed_entity_decl_handler',
    'xml_set_notation_decl_handler',
    'xml_set_external_entity_ref_handler',
    'xml_set_start_namespace_decl_handler',
    'xml_set_end_namespace_decl_handler',
    'xml_parse',
    'xml_parse_into_struct',
    'xml_get_error_code',
    'xml_error_string',
    'xml_get_current_line_number',
    'xml_get_current_column_number',
    'xml_get_current_byte_index',
    'xml_parser_free',
    'xml_parser_set_option',
    'xml_parser_get_option',
    'xmlwriter_open_uri',
    'xmlwriter_open_memory',
    'xmlwriter_set_indent',
    'xmlwriter_set_indent_string',
    'xmlwriter_start_comment',
    'xmlwriter_end_comment',
    'xmlwriter_start_attribute',
    'xmlwriter_end_attribute',
    'xmlwriter_write_attribute',
    'xmlwriter_start_attribute_ns',
    'xmlwriter_write_attribute_ns',
    'xmlwriter_start_element',
    'xmlwriter_end_element',
    'xmlwriter_full_end_element',
    'xmlwriter_start_element_ns',
    'xmlwriter_write_element',
    'xmlwriter_write_element_ns',
    'xmlwriter_start_pi',
    'xmlwriter_end_pi',
    'xmlwriter_write_pi',
    'xmlwriter_start_cdata',
    'xmlwriter_end_cdata',
    'xmlwriter_write_cdata',
    'xmlwriter_text',
    'xmlwriter_write_raw',
    'xmlwriter_start_document',
    'xmlwriter_end_document',
    'xmlwriter_write_comment',
    'xmlwriter_start_dtd',
    'xmlwriter_end_dtd',
    'xmlwriter_write_dtd',
    'xmlwriter_start_dtd_element',
    'xmlwriter_end_dtd_element',
    'xmlwriter_write_dtd_element',
    'xmlwriter_start_dtd_attlist',
    'xmlwriter_end_dtd_attlist',
    'xmlwriter_write_dtd_attlist',
    'xmlwriter_start_dtd_entity',
    'xmlwriter_end_dtd_entity',
    'xmlwriter_write_dtd_entity',
    'xmlwriter_output_memory',
    'xmlwriter_flush',
    'curl_close',
    'curl_copy_handle',
    'curl_errno',
    'curl_error',
    'curl_escape',
    'curl_unescape',
    'curl_multi_setopt',
    'curl_file_create',
    'curl_getinfo',
    'curl_init',
    'curl_multi_add_handle',
    'curl_multi_close',
    'curl_multi_errno',
    'curl_multi_exec',
    'curl_multi_getcontent',
    'curl_multi_info_read',
    'curl_multi_init',
    'curl_multi_remove_handle',
    'curl_multi_select',
    'curl_multi_strerror',
    'curl_pause',
    'curl_reset',
    'curl_setopt_array',
    'curl_setopt',
    'curl_share_close',
    'curl_share_errno',
    'curl_share_init',
    'curl_share_setopt',
    'curl_share_strerror',
    'curl_strerror',
    'curl_version',
    'mb_language',
    'mb_internal_encoding',
    'mb_http_input',
    'mb_http_output',
    'mb_detect_order',
    'mb_substitute_character',
    'mb_preferred_mime_name',
    'mb_parse_str',            
    'mb_output_handler',
    'mb_str_split',
    'mb_strlen',
    'mb_strpos',
    'mb_strrpos',
    'mb_stripos',
    'mb_strripos',
    'mb_strstr',
    'mb_strrchr',
    'mb_stristr',
    'mb_strrichr',
    'mb_substr_count',
    'mb_strcut',
    'mb_strwidth',
    'mb_strimwidth',
    'mb_convert_encoding',
    'mb_convert_case',
    'mb_strtoupper',
    'mb_strtolower',
    'mb_detect_encoding',
    'mb_list_encodings',
    'mb_encoding_aliases',
    'mb_encode_mimeheader',
    'mb_decode_mimeheader',
    'mb_convert_kana',
    'mb_convert_variables',
    'mb_encode_numericentity',
    'mb_decode_numericentity',
    'mb_send_mail',
    'mb_get_info',
    'mb_check_encoding',
    'mb_scrub',
    'mb_ord',
    'mb_chr',
    'mb_regex_encoding',
    'mb_ereg_search_getregs',
    'mb_ereg_search_getpos',
    'mb_ereg_search_setpos',
    'mb_regex_set_options',
    'openssl_x509_export_to_file',
    'openssl_x509_export',
    'openssl_x509_fingerprint',
    'openssl_x509_check_private_key',
    'openssl_x509_verify',
    'openssl_x509_parse',
    'openssl_x509_checkpurpose',
    'openssl_x509_read',
    'openssl_x509_free',
    'openssl_pkcs12_export_to_file',
    'openssl_pkcs12_export',
    'openssl_pkcs12_read',
    'openssl_csr_export_to_file',
    'openssl_csr_export',
    'openssl_csr_sign',
    'openssl_csr_new',
    'openssl_csr_get_subject',
    'openssl_csr_get_public_key',
    'openssl_pkey_new',
    'openssl_pkey_export_to_file',
    'openssl_pkey_export',
    'openssl_pkey_get_public',
    'openssl_get_publickey',
    'openssl_pkey_free',
    'openssl_free_key',
    'openssl_pkey_get_private',
    'openssl_get_privatekey',
    'openssl_pkey_get_details',
    'openssl_pbkdf2',
    'openssl_pkcs7_verify',
    'openssl_pkcs7_encrypt',
    'openssl_pkcs7_sign',
    'openssl_pkcs7_decrypt',
    'openssl_pkcs7_read',
    'openssl_cms_verify',
    'openssl_cms_sign',
    'openssl_cms_read',
    'openssl_error_string',
    'openssl_sign',
    'openssl_verify',
    'openssl_seal',
    'openssl_open',
    'openssl_get_md_methods',
    'openssl_get_cipher_methods',
    'openssl_get_curve_names',
    'openssl_digest',
    'openssl_cipher_iv_length',
    'openssl_dh_compute_key',
    'openssl_pkey_derive',
    'openssl_random_pseudo_bytes',
    'openssl_spki_new',
    'openssl_spki_verify',
    'openssl_spki_export',
    'openssl_spki_export_challenge',
    'openssl_get_cert_locations',
    'xdebug_break',
    'xdebug_call_class',
    'xdebug_call_file',
    'xdebug_call_function',
    'xdebug_call_line',
    'xdebug_code_coverage_started',
    'xdebug_connect_to_client',
    'xdebug_debug_zval',
    'xdebug_debug_zval_stdout',
    'xdebug_dump_superglobals',
    'xdebug_get_code_coverage',
    'xdebug_get_collected_errors',
    'xdebug_get_function_count',
    'xdebug_get_function_stack',
    'xdebug_get_gc_run_count',
    'xdebug_get_gc_total_collected_roots',
    'xdebug_get_gcstats_filename',
    'xdebug_get_headers',
    'xdebug_get_monitored_functions',
    'xdebug_get_profiler_filename',
    'xdebug_get_stack_depth',
    'xdebug_get_tracefile_name',
    'xdebug_info',
    'xdebug_is_debugger_active',
    'xdebug_memory_usage',
    'xdebug_notify',
    'xdebug_peak_memory_usage',
    'xdebug_print_function_stack',
    'xdebug_set_filter',
    'xdebug_start_code_coverage',
    'xdebug_start_error_collection',
    'xdebug_start_function_monitor',
    'xdebug_start_gcstats',
    'xdebug_start_trace',
    'xdebug_stop_code_coverage',
    'xdebug_stop_error_collection',
    'xdebug_stop_function_monitor',
    'xdebug_stop_gcstats',
    'xdebug_stop_trace',
    'xdebug_time_index',
    'xdebug_var_dump',
    'opcache_reset',
    'opcache_get_status',
    'opcache_compile_file',
    'opcache_invalidate',
    'opcache_get_configuration',
    'opcache_is_script_cached',
    'dl',
    'cli_set_process_title',
    'cli_get_process_title',
);


$ENCODEFUNCLIST = array(
    'iconv_mime_encode'=> [[2], ["iconv_mime_decode","iconv_mime_decode_headers"]],
    'base64_encode'=> [[1], ["base64_decode"]],
    'htmlspecialchars'=> [[1], ["htmlspecialchars_decode"]],
    'htmlentities'=> [[1], ["html_entity_decode"]],
    'bin2hex'=> [[1], ["hex2bin"]],
    'ord'=> [[1], ["chr"]],
    'chr'=> [[1], ["ord"]],
    'addcslashes'=> [[1], ["stripcslashes"]],
    'addslashes'=> [[1], ["stripslashes"]],
    'str_rot13'=> [[1], ["str_rot13"]],
    'pack'=> [[999], ["unpack"]],
    'convert_uuencode'=> [[1], ["convert_uudecode"]],
    'serialize'=> [[1], ["unserialize"]],
    'zlib_encode'=> [[1], ["zlib_decode"]],
    'gzdeflate'=> [[1], ["gzinflate"]],
    'gzencode'=> [[1], ["gzdecode"]],
    'gzcompress'=> [[1], ["gzuncompress"]],
    'deflate_add'=> [[1], ["inflate_add"]],
    'mb_convert_encoding'=> [[1], ["mb_convert_encoding"]],
    'mb_convert_variables'=> [[1], ["mb_convert_variables"]],
);

$DECODEFUNCLIST = array(
    'iconv_mime_decode'=> [[1], "iconv_mime_encode"],
    'iconv_mime_decode_headers'=> [[1], "iconv_mime_encode"],
    'base64_decode'=> [[1], ["base64_encode"]],
    'htmlspecialchars_decode'=> [[1], ["htmlspecialchars"]],
    'html_entity_decode'=> [[1], ["htmlentities"]],
    'hex2bin'=> [[1], ["bin2hex"]],
    'chr'=> [[1], ["ord"]],
    'ord'=> [[1], ["chr"]],
    'stripcslashes'=> [[1], ["addcslashes"]],
    'stripslashes'=> [[1], ["addslashes"]],
    'str_rot13'=> [[1], ["str_rot13"]],
    'unpack'=> [[2], ["pack"]],
    'convert_uudecode'=> [[1], ["convert_uuencode"]],
    'unserialize'=> [[1], ["serialize"]],
    'zlib_decode'=> [[1], ["zlib_encode"]],
    'gzinflate'=> [[1], ["gzdeflate"]],
    'gzdecode'=> [[1], ["gzencode"]],
    'gzuncompress'=> [[1], ["gzcompress"]],
    'inflate_add'=> [[1], ["deflate_add"]],
    'mb_convert_encoding'=> [[1], ["mb_convert_encoding"]],
    'mb_convert_variables'=> [[1], ["mb_convert_variables"]],
);

$TAINTFUNCLIST = array(
    'strtoupper' => [[1], []],
    'strtolower' => [[1], []],
    'mysqli_real_escape_string' => [[0], []],
    'mysql_real_escape_string' => [[0], []],
    'trim' => [[1], []],
    'rtrim' => [[1], []],
    'ltrim' => [[1], []],
    'json_encode' => [[1],[]],
    'json_decode' => [[1],[]],
    'strip_tags' => [[1],[]],
    'sprintf' => [[0], []],
    'vsprintf' => [[2], []],
    'get_object_vars' => [[1], []],                 
    'get_mangled_object_vars' => [[1], []],
    'readline_read_history' => [[1], []],           
    'iterator_to_array' => [[1], []],               
    'shuffle' => [[1], []],                        
    'wordwrap' => [[1], []],                        
    'explode' => [[2], []],                         
    'implode' => [[2], []],                         
    'join' => [[2], []],                            
    'stristr' => [[2], []],                         
    'strstr' => [[2], []],                          
    'strchr' => [[2], []],                          
    'strrchr' => [[2], []],                         
    'substr' => [[1], []],                          
    'substr_replace' => [[1,2], []],                
    'chunk_split' => [[1], []],                     
    'ucfirst' => [[1], []],                         
    'lcfirst' => [[1], []],                         
    'ucwords' => [[1], []],                         
    'strtr' => [[1], []],                           
    'strrev' => [[1], []],                          
    'str_replace' => [[3], []],                     
    'str_ireplace' => [[3], []],                    
    'str_pad' => [[1], []],                         
    'mb_substr' => [[1], []],
);

$ARRAYMODELINGLFUNCLIST = array(
    'array_keys' => [[1], []],                      
    'parse_str'  => [[1], []],                      
    'compact' => [[1], []],
    'extract' => [[1], []],                         
    'sort' => [[1], []],
    'array_pad' => [[3], []],                       
    'in_array' => [[1,2], []],           
    'preg_match' => [[2], []],
    'preg_match_all' => [[2], []],                   
);

$ARRAYFUNCLIST = array(
    'array_push' => [[0], []],          
    'krsort' => [[1], []],              
    'ksort' => [[1], []],
    'natsort' => [[1], []],
    'natcasesort' => [[1], []],
    'asort' => [[1], []],
    'arsort' => [[1], []],
    'rsort' => [[1], []],
    'end' => [[1], []],
    'prev' => [[1], []],
    'next' => [[1], []],
    'reset' => [[1], []],
    'current' => [[1], []],
    'pos' => [[1], []],
    'key' => [[1], []],
    'array_search' => [[2], []],
    'array_fill' => [[1], []],                     
    'array_fill_keys' => [[1], []],                
    'array_pop' => [[1], []],                      
    'array_shift' => [[1], []],                    
    'array_unshift' => [[1], []],                  
    'array_splice' => [[1], []],                   
    'array_slice' => [[1], []],                    
    'array_merge' => [[1], []],                    
    'array_merge_recursive' => [[1], []],          
    'array_replace' => [[1], []],                  
    'array_replace_recursive' => [[1], []],        
    'array_key_first' => [[1], []],                
    'array_key_last' => [[1], []],                 
    'array_values' => [[1], []],                   
    'array_count_values' => [[1], []],             
    'array_column' => [[1], []],                   
    'array_reverse' => [[1], []],                  
    'array_flip' => [[1], []],                     
    'array_change_key_case' => [[1], []],          
    'array_unique' => [[1], []],                   
    'array_intersect_key' => [[1], []],            
    'array_intersect' => [[1], []],                
    'array_intersect_assoc' => [[1], []],          
    'array_intersect_uassoc' => [[1], []],         
    'array_diff_key' => [[1], []],                 
    'array_diff' => [[1], []],                     
    'array_diff_assoc' => [[1], []],               
    'array_multisort' => [[1], []],                
    'array_rand' => [[1], []],                     
    'array_sum' => [[1], []],                      
    'array_product' => [[1], []],                  
    'array_key_exists' => [[1], []],               
    'key_exists' => [[1], []],                     
    'array_chunk' => [[1], []],                    
    'array_combine' => [[1], []],                  
);

$TAINTSOURCEFUNCLIST = array(
    'readline' => [],                 
);


$EXCEPTIONSCLASSLIST = array(
    'Exception',
);

// $INTERNALFUNCLIST = get_defined_functions()['internal'];

// $INTERNALCLASS = get_declared_classes();

$FILETYPES = array(                        // filetypes to scan
    'php',
    // 'inc',
    // 'phps',
    // 'php4',
    // 'php5',
    // 'php7',
    // 'php8',
    //'html', 
    //'htm', 
    //'txt',
    // 'phtml',
    // 'tpl',
    // 'cgi',
    // 'test',
    // 'module',
    // 'plugin'
);

$debugFlag = TRUE;

$TAINTSOURCE = ["_GET", "_POST", "_REQUEST", "GLOBALS", "_SERVER", "_COOKIE", "_FILES"];

$STADYMPATH = str_replace('\\', '/', dirname(dirname(__FILE__)));

define("STAPATH", $STADYMPATH);

const IS_UNUSED             =  800;       
const IS_CONST              =  801;   
const IS_TMP_VAR            =  802;   
const IS_VAR                =  803;   
const IS_CV                 =  804;    

const IS_LOCAL              = 901;
const IS_ARRAY              = 902;
const IS_CONST_ARRAY        = 903;
const IS_OBJECT             = 904;
const IS_GLOBAL_UNBIND      = 905;
const IS_INIT               = 906;
const IS_INTERFUNC          = 907;
const IS_GLOBAL             = 908;



const __construct           = (1 << 1);
const __destruct            = (1 << 2);
const __call                = (1 << 3);
const __callstatic          = (1 << 4);
const __get                 = (1 << 5);
const __set                 = (1 << 6);
const __isset               = (1 << 7);
const __unset               = (1 << 8);
const __sleep               = (1 << 9);
const __wakeup              = (1 << 10);
const __serialize           = (1 << 11);
const __unserialize         = (1 << 12);
const __tostring            = (1 << 13);
const __invoke              = (1 << 14);
const __set_state           = (1 << 15);
const __clone               = (1 << 16);
const __debugInfo           = (1 << 17);



const ZEND_NOP                         =      0;
const ZEND_ADD                         =      1;
const ZEND_SUB                         =      2;
const ZEND_MUL                         =      3;
const ZEND_DIV                         =      4;
const ZEND_MOD                         =      5;
const ZEND_SL                          =      6;
const ZEND_SR                          =      7;
const ZEND_CONCAT                      =      8;
const ZEND_BW_OR                       =      9;
const ZEND_BW_AND                      =     10;
const ZEND_BW_XOR                      =     11;
const ZEND_POW                         =     12;
const ZEND_BW_NOT                      =     13;
const ZEND_BOOL_NOT                    =     14;
const ZEND_BOOL_XOR                    =     15;
const ZEND_IS_IDENTICAL                =     16;
const ZEND_IS_NOT_IDENTICAL            =     17;
const ZEND_IS_EQUAL                    =     18;
const ZEND_IS_NOT_EQUAL                =     19;
const ZEND_IS_SMALLER                  =     20;
const ZEND_IS_SMALLER_OR_EQUAL         =     21;
const ZEND_ASSIGN                      =     22;
const ZEND_ASSIGN_DIM                  =     23;
const ZEND_ASSIGN_OBJ                  =     24;
const ZEND_ASSIGN_STATIC_PROP          =     25;
const ZEND_ASSIGN_OP                   =     26;
const ZEND_ASSIGN_DIM_OP               =     27;
const ZEND_ASSIGN_OBJ_OP               =     28;
const ZEND_ASSIGN_STATIC_PROP_OP       =     29;
const ZEND_ASSIGN_REF                  =     30;
const ZEND_QM_ASSIGN                   =     31;
const ZEND_ASSIGN_OBJ_REF              =     32;
const ZEND_ASSIGN_STATIC_PROP_REF      =     33;
const ZEND_PRE_INC                     =     34;
const ZEND_PRE_DEC                     =     35;
const ZEND_POST_INC                    =     36;
const ZEND_POST_DEC                    =     37;
const ZEND_PRE_INC_STATIC_PROP         =     38;
const ZEND_PRE_DEC_STATIC_PROP         =     39;
const ZEND_POST_INC_STATIC_PROP        =     40;
const ZEND_POST_DEC_STATIC_PROP        =     41;
const ZEND_JMP                         =     42;
const ZEND_JMPZ                        =     43;
const ZEND_JMPNZ                       =     44;
const ZEND_JMPZNZ                      =     45;
const ZEND_JMPZ_EX                     =     46;
const ZEND_JMPNZ_EX                    =     47;
const ZEND_CASE                        =     48;
const ZEND_CHECK_VAR                   =     49;
const ZEND_SEND_VAR_NO_REF_EX          =     50;
const ZEND_CAST                        =     51;
const ZEND_BOOL                        =     52;
const ZEND_FAST_CONCAT                 =     53;
const ZEND_ROPE_INIT                   =     54;
const ZEND_ROPE_ADD                    =     55;
const ZEND_ROPE_END                    =     56;
const ZEND_BEGIN_SILENCE               =     57;
const ZEND_END_SILENCE                 =     58;
const ZEND_INIT_FCALL_BY_NAME          =     59;
const ZEND_DO_FCALL                    =     60;
const ZEND_INIT_FCALL                  =     61;
const ZEND_RETURN                      =     62;
const ZEND_RECV                        =     63;
const ZEND_RECV_INIT                   =     64;
const ZEND_SEND_VAL                    =     65;
const ZEND_SEND_VAR_EX                 =     66;
const ZEND_SEND_REF                    =     67;
const ZEND_NEW                         =     68;
const ZEND_INIT_NS_FCALL_BY_NAME       =     69;
const ZEND_FREE                        =     70;
const ZEND_INIT_ARRAY                  =     71;
const ZEND_ADD_ARRAY_ELEMENT           =     72;
const ZEND_INCLUDE_OR_EVAL             =     73;
const ZEND_UNSET_VAR                   =     74;
const ZEND_UNSET_DIM                   =     75;
const ZEND_UNSET_OBJ                   =     76;
const ZEND_FE_RESET_R                  =     77;
const ZEND_FE_FETCH_R                  =     78;
const ZEND_EXIT                        =     79;
const ZEND_FETCH_R                     =     80;
const ZEND_FETCH_DIM_R                 =     81;
const ZEND_FETCH_OBJ_R                 =     82;
const ZEND_FETCH_W                     =     83;
const ZEND_FETCH_DIM_W                 =     84;
const ZEND_FETCH_OBJ_W                 =     85;
const ZEND_FETCH_RW                    =     86;
const ZEND_FETCH_DIM_RW                =     87;
const ZEND_FETCH_OBJ_RW                =     88;
const ZEND_FETCH_IS                    =     89;
const ZEND_FETCH_DIM_IS                =     90;
const ZEND_FETCH_OBJ_IS                =     91;
const ZEND_FETCH_FUNC_ARG              =     92;
const ZEND_FETCH_DIM_FUNC_ARG          =     93;
const ZEND_FETCH_OBJ_FUNC_ARG          =     94;
const ZEND_FETCH_UNSET                 =     95;
const ZEND_FETCH_DIM_UNSET             =     96;
const ZEND_FETCH_OBJ_UNSET             =     97;
const ZEND_FETCH_LIST_R                =     98;
const ZEND_FETCH_CONSTANT              =     99;
const ZEND_CHECK_FUNC_ARG              =    100;
const ZEND_EXT_STMT                    =    101;
const ZEND_EXT_FCALL_BEGIN             =    102;
const ZEND_EXT_FCALL_END               =    103;
const ZEND_EXT_NOP                     =    104;
const ZEND_TICKS                       =    105;
const ZEND_SEND_VAR_NO_REF             =    106;
const ZEND_CATCH                       =    107;
const ZEND_THROW                       =    108;
const ZEND_FETCH_CLASS                 =    109;
const ZEND_CLONE                       =    110;
const ZEND_RETURN_BY_REF               =    111;
const ZEND_INIT_METHOD_CALL            =    112;
const ZEND_INIT_STATIC_METHOD_CALL     =    113;
const ZEND_ISSET_ISEMPTY_VAR           =    114;
const ZEND_ISSET_ISEMPTY_DIM_OBJ       =    115;
const ZEND_SEND_VAL_EX                 =    116;
const ZEND_SEND_VAR                    =    117;
const ZEND_INIT_USER_CALL              =    118;
const ZEND_SEND_ARRAY                  =    119;
const ZEND_SEND_USER                   =    120;
const ZEND_STRLEN                      =    121;
const ZEND_DEFINED                     =    122;
const ZEND_TYPE_CHECK                  =    123;
const ZEND_VERIFY_RETURN_TYPE          =    124;
const ZEND_FE_RESET_RW                 =    125;
const ZEND_FE_FETCH_RW                 =    126;
const ZEND_FE_FREE                     =    127;
const ZEND_INIT_DYNAMIC_CALL           =    128;
const ZEND_DO_ICALL                    =    129;
const ZEND_DO_UCALL                    =    130;
const ZEND_DO_FCALL_BY_NAME            =    131;
const ZEND_PRE_INC_OBJ                 =    132;
const ZEND_PRE_DEC_OBJ                 =    133;
const ZEND_POST_INC_OBJ                =    134;
const ZEND_POST_DEC_OBJ                =    135;
const ZEND_ECHO                        =    136;
const ZEND_OP_DATA                     =    137;
const ZEND_INSTANCEOF                  =    138;
const ZEND_GENERATOR_CREATE            =    139;
const ZEND_MAKE_REF                    =    140;
const ZEND_DECLARE_FUNCTION            =    141;
const ZEND_DECLARE_LAMBDA_FUNCTION     =    142;
const ZEND_DECLARE_CONST               =    143;
const ZEND_DECLARE_CLASS               =    144;
const ZEND_DECLARE_CLASS_DELAYED       =    145;
const ZEND_DECLARE_ANON_CLASS          =    146;
const ZEND_ADD_ARRAY_UNPACK            =    147;
const ZEND_ISSET_ISEMPTY_PROP_OBJ      =    148;
const ZEND_HANDLE_EXCEPTION            =    149;
const ZEND_USER_OPCODE                 =    150;
const ZEND_ASSERT_CHECK                =    151;
const ZEND_JMP_SET                     =    152;
const ZEND_UNSET_CV                    =    153;
const ZEND_ISSET_ISEMPTY_CV            =    154;
const ZEND_FETCH_LIST_W                =    155;
const ZEND_SEPARATE                    =    156;
const ZEND_FETCH_CLASS_NAME            =    157;
const ZEND_CALL_TRAMPOLINE             =    158;
const ZEND_DISCARD_EXCEPTION           =    159;
const ZEND_YIELD                       =    160;
const ZEND_GENERATOR_RETURN            =    161;
const ZEND_FAST_CALL                   =    162;
const ZEND_FAST_RET                    =    163;
const ZEND_RECV_VARIADIC               =    164;
const ZEND_SEND_UNPACK                 =    165;
const ZEND_YIELD_FROM                  =    166;
const ZEND_COPY_TMP                    =    167;
const ZEND_BIND_GLOBAL                 =    168;
const ZEND_COALESCE                    =    169;
const ZEND_SPACESHIP                   =    170;
const ZEND_FUNC_NUM_ARGS               =    171;
const ZEND_FUNC_GET_ARGS               =    172;
const ZEND_FETCH_STATIC_PROP_R         =    173;
const ZEND_FETCH_STATIC_PROP_W         =    174;
const ZEND_FETCH_STATIC_PROP_RW        =    175;
const ZEND_FETCH_STATIC_PROP_IS        =    176;
const ZEND_FETCH_STATIC_PROP_FUNC_ARG  =    177;
const ZEND_FETCH_STATIC_PROP_UNSET     =    178;
const ZEND_UNSET_STATIC_PROP           =    179;
const ZEND_ISSET_ISEMPTY_STATIC_PROP   =    180;
const ZEND_FETCH_CLASS_CONSTANT        =    181;
const ZEND_BIND_LEXICAL                =    182;
const ZEND_BIND_STATIC                 =    183;
const ZEND_FETCH_THIS                  =    184;
const ZEND_SEND_FUNC_ARG               =    185;
const ZEND_ISSET_ISEMPTY_THIS          =    186;
const ZEND_SWITCH_LONG                 =    187;
const ZEND_SWITCH_STRING               =    188;
const ZEND_IN_ARRAY                    =    189;
const ZEND_COUNT                       =    190;
const ZEND_GET_CLASS                   =    191;
const ZEND_GET_CALLED_CLASS            =    192;
const ZEND_GET_TYPE                    =    193;
const ZEND_ARRAY_KEY_EXISTS            =    194;
const ZEND_MATCH                       =    195;
const ZEND_CASE_STRICT                 =    196;
const ZEND_MATCH_ERROR                 =    197;
const ZEND_JMP_NULL                    =    198;
const ZEND_CHECK_UNDEF_ARGS            =    199;







$INTERNALFUNCLIST = array
(
    'zend_version',
    'func_num_args',
    'func_get_arg',
    'func_get_args',
    'strlen',
    'strcmp',
    'strncmp',
    'strcasecmp',
    'strncasecmp',
    'error_reporting',
    'define',
    'defined',
    'get_class',
    'get_called_class',
    'get_parent_class',
    'is_subclass_of',
    'is_a',
    'get_class_vars',
    'get_object_vars',
    'get_mangled_object_vars',
    'get_class_methods',
    'method_exists',
    'property_exists',
    'class_exists',
    'interface_exists',
    'trait_exists',
    'function_exists',
    'class_alias',
    'get_included_files',
    'get_required_files',
    'trigger_error',
    'user_error',
    'set_error_handler',
    'restore_error_handler',
    'set_exception_handler',
    'restore_exception_handler',
    'get_declared_classes',
    'get_declared_traits',
    'get_declared_interfaces',
    'get_defined_functions',
    'get_defined_vars',
    'get_resource_type',
    'get_resource_id',
    'get_resources',
    'get_loaded_extensions',
    'get_defined_constants',
    'debug_backtrace',
    'debug_print_backtrace',
    'extension_loaded',
    'get_extension_funcs',
    'gc_mem_caches',
    'gc_collect_cycles',
    'gc_enabled',
    'gc_enable',
    'gc_disable',
    'gc_status',
    'bcadd',
    'bcsub',
    'bcmul',
    'bcdiv',
    'bcmod',
    'bcpowmod',
    'bcpow',
    'bcsqrt',
    'bccomp',
    'bcscale',
    'cal_days_in_month',
    'cal_from_jd',
    'cal_info',
    'cal_to_jd',
    'easter_date',
    'easter_days',
    'frenchtojd',
    'gregoriantojd',
    'jddayofweek',
    'jdmonthname',
    'jdtofrench',
    'jdtogregorian',
    'jdtojewish',
    'jdtojulian',
    'jdtounix',
    'jewishtojd',
    'juliantojd',
    'unixtojd',
    'ctype_alnum',
    'ctype_alpha',
    'ctype_cntrl',
    'ctype_digit',
    'ctype_lower',
    'ctype_graph',
    'ctype_print',
    'ctype_punct',
    'ctype_space',
    'ctype_upper',
    'ctype_xdigit',
    'strtotime',
    'date',
    'idate',
    'gmdate',
    'mktime',
    'gmmktime',
    'checkdate',
    'strftime',
    'gmstrftime',
    'time',
    'localtime',
    'getdate',
    'date_create',
    'date_create_immutable',
    'date_create_from_format',
    'date_create_immutable_from_format',
    'date_parse',
    'date_parse_from_format',
    'date_get_last_errors',
    'date_format',
    'date_modify',
    'date_add',
    'date_sub',
    'date_timezone_get',
    'date_timezone_set',
    'date_offset_get',
    'date_diff',
    'date_time_set',
    'date_date_set',
    'date_isodate_set',
    'date_timestamp_set',
    'date_timestamp_get',
    'timezone_open',
    'timezone_name_get',
    'timezone_name_from_abbr',
    'timezone_offset_get',
    'timezone_transitions_get',
    'timezone_location_get',
    'timezone_identifiers_list',
    'timezone_abbreviations_list',
    'timezone_version_get',
    'date_interval_create_from_date_string',
    'date_interval_format',
    'date_default_timezone_set',
    'date_default_timezone_get',
    'date_sunrise',
    'date_sunset',
    'date_sun_info',
    'filter_has_var',
    'filter_input',
    'filter_var',
    'filter_input_array',
    'filter_var_array',
    'filter_list',
    'filter_id',
    'hash',
    'hash_file',
    'hash_hmac',
    'hash_hmac_file',
    'hash_init',
    'hash_update',
    'hash_update_stream',
    'hash_update_file',
    'hash_final',
    'hash_copy',
    'hash_algos',
    'hash_hmac_algos',
    'hash_pbkdf2',
    'hash_equals',
    'hash_hkdf',
    'mhash_get_block_size',
    'mhash_get_hash_name',
    'mhash_keygen_s2k',
    'mhash_count',
    'mhash',
    'iconv_strlen',
    'iconv_substr',
    'iconv_strpos',
    'iconv_strrpos',
    'iconv_mime_encode',
    'iconv_mime_decode',
    'iconv_mime_decode_headers',
    'iconv',
    'iconv_set_encoding',
    'iconv_get_encoding',
    'json_encode',
    'json_decode',
    'json_last_error',
    'json_last_error_msg',
    'preg_match',
    'preg_match_all',
    'preg_replace',
    'preg_filter',
    'preg_replace_callback',
    'preg_replace_callback_array',
    'preg_split',
    'preg_quote',
    'preg_grep',
    'preg_last_error',
    'preg_last_error_msg',
    'readline',
    'readline_info',
    'readline_add_history',
    'readline_clear_history',
    'readline_list_history',
    'readline_read_history',
    'readline_write_history',
    'readline_completion_function',
    'session_name',
    'session_module_name',
    'session_save_path',
    'session_id',
    'session_create_id',
    'session_regenerate_id',
    'session_decode',
    'session_encode',
    'session_destroy',
    'session_unset',
    'session_gc',
    'session_get_cookie_params',
    'session_write_close',
    'session_abort',
    'session_reset',
    'session_status',
    'session_register_shutdown',
    'session_commit',
    'session_set_save_handler',
    'session_cache_limiter',
    'session_cache_expire',
    'session_set_cookie_params',
    'session_start',
    'class_implements',
    'class_parents',
    'class_uses',
    'spl_autoload',
    'spl_autoload_call',
    'spl_autoload_extensions',
    'spl_autoload_functions',
    'spl_autoload_register',
    'spl_autoload_unregister',
    'spl_classes',
    'spl_object_hash',
    'spl_object_id',
    'iterator_apply',
    'iterator_count',
    'iterator_to_array',
    'set_time_limit',
    'header_register_callback',
    'ob_start',
    'ob_flush',
    'ob_clean',
    'ob_end_flush',
    'ob_end_clean',
    'ob_get_flush',
    'ob_get_clean',
    'ob_get_contents',
    'ob_get_level',
    'ob_get_length',
    'ob_list_handlers',
    'ob_get_status',
    'ob_implicit_flush',
    'output_reset_rewrite_vars',
    'output_add_rewrite_var',
    'stream_wrapper_register',
    'stream_register_wrapper',
    'stream_wrapper_unregister',
    'stream_wrapper_restore',
    'array_push',
    'krsort',
    'ksort',
    'count',
    'sizeof',
    'natsort',
    'natcasesort',
    'asort',
    'arsort',
    'sort',
    'rsort',
    'usort',
    'uasort',
    'uksort',
    'end',
    'prev',
    'next',
    'reset',
    'current',
    'pos',
    'key',
    'min',
    'max',
    'array_walk',
    'array_walk_recursive',
    'in_array',
    'array_search',
    'extract',
    'compact',
    'array_fill',
    'array_fill_keys',
    'range',
    'shuffle',
    'array_pop',
    'array_shift',
    'array_unshift',
    'array_splice',
    'array_slice',
    'array_merge',
    'array_merge_recursive',
    'array_replace',
    'array_replace_recursive',
    'array_keys',
    'array_key_first',
    'array_key_last',
    'array_values',
    'array_count_values',
    'array_column',
    'array_reverse',
    'array_pad',
    'array_flip',
    'array_change_key_case',
    'array_unique',
    'array_intersect_key',
    'array_intersect_ukey',
    'array_intersect',
    'array_uintersect',
    'array_intersect_assoc',
    'array_uintersect_assoc',
    'array_intersect_uassoc',
    'array_uintersect_uassoc',
    'array_diff_key',
    'array_diff_ukey',
    'array_diff',
    'array_udiff',
    'array_diff_assoc',
    'array_diff_uassoc',
    'array_udiff_assoc',
    'array_udiff_uassoc',
    'array_multisort',
    'array_rand',
    'array_sum',
    'array_product',
    'array_reduce',
    'array_filter',
    'array_map',
    'array_key_exists',
    'key_exists',
    'array_chunk',
    'array_combine',
    'base64_encode',
    'base64_decode',
    'constant',
    'ip2long',
    'long2ip',
    'getenv',
    'putenv',
    'getopt',
    'flush',
    'sleep',
    'usleep',
    'time_nanosleep',
    'time_sleep_until',
    'get_current_user',
    'get_cfg_var',
    'error_log',
    'error_get_last',
    'error_clear_last',
    'call_user_func',
    'call_user_func_array',
    'forward_static_call',
    'forward_static_call_array',
    'register_shutdown_function',
    'highlight_file',
    'show_source',
    'php_strip_whitespace',
    'highlight_string',
    'ini_get',
    'ini_get_all',
    'ini_set',
    'ini_alter',
    'ini_restore',
    'set_include_path',
    'get_include_path',
    'print_r',
    'connection_aborted',
    'connection_status',
    'ignore_user_abort',
    'getservbyname',
    'getservbyport',
    'getprotobyname',
    'getprotobynumber',
    'register_tick_function',
    'unregister_tick_function',
    'is_uploaded_file',
    'move_uploaded_file',
    'parse_ini_file',
    'parse_ini_string',
    'get_browser',
    'crc32',
    'crypt',
    'gethostname',
    'gethostbyaddr',
    'gethostbyname',
    'gethostbynamel',
    'dns_check_record',
    'checkdnsrr',
    'dns_get_record',
    'dns_get_mx',
    'getmxrr',
    'net_get_interfaces',
    'ftok',
    'hrtime',
    'lcg_value',
    'md5',
    'md5_file',
    'getmyuid',
    'getmygid',
    'getmypid',
    'getmyinode',
    'getlastmod',
    'sha1',
    'sha1_file',
    'openlog',
    'closelog',
    'syslog',
    'inet_ntop',
    'inet_pton',
    'metaphone',
    'header',
    'header_remove',
    'setrawcookie',
    'setcookie',
    'http_response_code',
    'headers_sent',
    'headers_list',
    'htmlspecialchars',
    'htmlspecialchars_decode',
    'html_entity_decode',
    'htmlentities',
    'get_html_translation_table',
    'assert',
    'assert_options',
    'bin2hex',
    'hex2bin',
    'strspn',
    'strcspn',
    'strcoll',
    'trim',
    'rtrim',
    'chop',
    'ltrim',
    'wordwrap',
    'explode',
    'implode',
    'join',
    'strtok',
    'strtoupper',
    'strtolower',
    'basename',
    'dirname',
    'pathinfo',
    'stristr',
    'strstr',
    'strchr',
    'strpos',
    'stripos',
    'strrpos',
    'strripos',
    'strrchr',
    'str_contains',
    'str_starts_with',
    'str_ends_with',
    'chunk_split',
    'substr',
    'substr_replace',
    'quotemeta',
    'ord',
    'chr',
    'ucfirst',
    'lcfirst',
    'ucwords',
    'strtr',
    'strrev',
    'similar_text',
    'addcslashes',
    'addslashes',
    'stripcslashes',
    'stripslashes',
    'str_replace',
    'str_ireplace',
    'hebrev',
    'nl2br',
    'strip_tags',
    'setlocale',
    'parse_str',
    'str_getcsv',
    'str_repeat',
    'count_chars',
    'strnatcmp',
    'localeconv',
    'strnatcasecmp',
    'substr_count',
    'str_pad',
    'sscanf',
    'str_rot13',
    'str_shuffle',
    'str_word_count',
    'str_split',
    'strpbrk',
    'substr_compare',
    'utf8_encode',
    'utf8_decode',
    'opendir',
    'dir',
    'closedir',
    'chdir',
    'getcwd',
    'rewinddir',
    'readdir',
    'scandir',
    'glob',
    'exec',
    'system',
    'passthru',
    'escapeshellcmd',
    'escapeshellarg',
    'shell_exec',
    'proc_nice',
    'flock',
    'get_meta_tags',
    'pclose',
    'popen',
    'readfile',
    'rewind',
    'rmdir',
    'umask',
    'fclose',
    'feof',
    'fgetc',
    'fgets',
    'fread',
    'fopen',
    'fscanf',
    'fpassthru',
    'ftruncate',
    'fstat',
    'fseek',
    'ftell',
    'fflush',
    'fwrite',
    'fputs',
    'mkdir',
    'rename',
    'copy',
    'tempnam',
    'tmpfile',
    'file',
    'file_get_contents',
    'unlink',
    'file_put_contents',
    'fputcsv',
    'fgetcsv',
    'realpath',
    'fnmatch',
    'sys_get_temp_dir',
    'fileatime',
    'filectime',
    'filegroup',
    'fileinode',
    'filemtime',
    'fileowner',
    'fileperms',
    'filesize',
    'filetype',
    'file_exists',
    'is_writable',
    'is_writeable',
    'is_readable',
    'is_executable',
    'is_file',
    'is_dir',
    'is_link',
    'stat',
    'lstat',
    'chown',
    'chgrp',
    'chmod',
    'touch',
    'clearstatcache',
    'disk_total_space',
    'disk_free_space',
    'diskfreespace',
    'realpath_cache_get',
    'realpath_cache_size',
    'sprintf',
    'printf',
    'vprintf',
    'vsprintf',
    'fprintf',
    'vfprintf',
    'fsockopen',
    'pfsockopen',
    'http_build_query',
    'image_type_to_mime_type',
    'image_type_to_extension',
    'getimagesize',
    'getimagesizefromstring',
    'phpinfo',
    'phpversion',
    'phpcredits',
    'php_sapi_name',
    'php_uname',
    'php_ini_scanned_files',
    'php_ini_loaded_file',
    'iptcembed',
    'iptcparse',
    'levenshtein',
    'readlink',
    'linkinfo',
    'symlink',
    'link',
    'mail',
    'abs',
    'ceil',
    'floor',
    'round',
    'sin',
    'cos',
    'tan',
    'asin',
    'acos',
    'atan',
    'atanh',
    'atan2',
    'sinh',
    'cosh',
    'tanh',
    'asinh',
    'acosh',
    'expm1',
    'log1p',
    'pi',
    'is_finite',
    'is_nan',
    'intdiv',
    'is_infinite',
    'pow',
    'exp',
    'log',
    'log10',
    'sqrt',
    'hypot',
    'deg2rad',
    'rad2deg',
    'bindec',
    'hexdec',
    'octdec',
    'decbin',
    'decoct',
    'dechex',
    'base_convert',
    'number_format',
    'fmod',
    'fdiv',
    'microtime',
    'gettimeofday',
    'getrusage',
    'pack',
    'unpack',
    'password_get_info',
    'password_hash',
    'password_needs_rehash',
    'password_verify',
    'password_algos',
    'proc_open',
    'proc_close',
    'proc_terminate',
    'proc_get_status',
    'quoted_printable_decode',
    'quoted_printable_encode',
    'mt_srand',
    'srand',
    'rand',
    'mt_rand',
    'mt_getrandmax',
    'getrandmax',
    'random_bytes',
    'random_int',
    'soundex',
    'stream_select',
    'stream_context_create',
    'stream_context_set_params',
    'stream_context_get_params',
    'stream_context_set_option',
    'stream_context_get_options',
    'stream_context_get_default',
    'stream_context_set_default',
    'stream_filter_prepend',
    'stream_filter_append',
    'stream_filter_remove',
    'stream_socket_client',
    'stream_socket_server',
    'stream_socket_accept',
    'stream_socket_get_name',
    'stream_socket_recvfrom',
    'stream_socket_sendto',
    'stream_socket_enable_crypto',
    'stream_socket_shutdown',
    'stream_socket_pair',
    'stream_copy_to_stream',
    'stream_get_contents',
    'stream_supports_lock',
    'stream_set_write_buffer',
    'set_file_buffer',
    'stream_set_read_buffer',
    'stream_set_blocking',
    'socket_set_blocking',
    'stream_get_meta_data',
    'socket_get_status',
    'stream_get_line',
    'stream_resolve_include_path',
    'stream_get_wrappers',
    'stream_get_transports',
    'stream_is_local',
    'stream_isatty',
    'sapi_windows_vt100_support',
    'stream_set_chunk_size',
    'stream_set_timeout',
    'socket_set_timeout',
    'gettype',
    'get_debug_type',
    'settype',
    'intval',
    'floatval',
    'doubleval',
    'boolval',
    'strval',
    'is_null',
    'is_resource',
    'is_bool',
    'is_int',
    'is_integer',
    'is_long',
    'is_float',
    'is_double',
    'is_numeric',
    'is_string',
    'is_array',
    'is_object',
    'is_scalar',
    'is_callable',
    'is_iterable',
    'is_countable',
    'uniqid',
    'parse_url',
    'urlencode',
    'urldecode',
    'rawurlencode',
    'rawurldecode',
    'get_headers',
    'stream_bucket_make_writeable',
    'stream_bucket_prepend',
    'stream_bucket_append',
    'stream_bucket_new',
    'stream_get_filters',
    'stream_filter_register',
    'convert_uuencode',
    'convert_uudecode',
    'var_dump',
    'var_export',
    'debug_zval_dump',
    'serialize',
    'unserialize',
    'memory_get_usage',
    'memory_get_peak_usage',
    'version_compare',
    'sapi_windows_cp_set',
    'sapi_windows_cp_get',
    'sapi_windows_cp_conv',
    'sapi_windows_cp_is_utf8',
    'sapi_windows_set_ctrl_handler',
    'sapi_windows_generate_ctrl_event',
    'token_get_all',
    'token_name',
    'zip_open',
    'zip_close',
    'zip_read',
    'zip_entry_open',
    'zip_entry_close',
    'zip_entry_read',
    'zip_entry_name',
    'zip_entry_compressedsize',
    'zip_entry_filesize',
    'zip_entry_compressionmethod',
    'ob_gzhandler',
    'zlib_get_coding_type',
    'gzfile',
    'gzopen',
    'readgzfile',
    'zlib_encode',
    'zlib_decode',
    'gzdeflate',
    'gzencode',
    'gzcompress',
    'gzinflate',
    'gzdecode',
    'gzuncompress',
    'gzwrite',
    'gzputs',
    'gzrewind',
    'gzclose',
    'gzeof',
    'gzgetc',
    'gzpassthru',
    'gzseek',
    'gztell',
    'gzread',
    'gzgets',
    'deflate_init',
    'deflate_add',
    'inflate_init',
    'inflate_add',
    'inflate_get_status',
    'inflate_get_read_len',
    'libxml_set_streams_context',
    'libxml_use_internal_errors',
    'libxml_get_last_error',
    'libxml_get_errors',
    'libxml_clear_errors',
    'libxml_disable_entity_loader',
    'libxml_set_external_entity_loader',
    'dom_import_simplexml',
    'pdo_drivers',
    'simplexml_load_file',
    'simplexml_load_string',
    'simplexml_import_dom',
    'xml_parser_create',
    'xml_parser_create_ns',
    'xml_set_object',
    'xml_set_element_handler',
    'xml_set_character_data_handler',
    'xml_set_processing_instruction_handler',
    'xml_set_default_handler',
    'xml_set_unparsed_entity_decl_handler',
    'xml_set_notation_decl_handler',
    'xml_set_external_entity_ref_handler',
    'xml_set_start_namespace_decl_handler',
    'xml_set_end_namespace_decl_handler',
    'xml_parse',
    'xml_parse_into_struct',
    'xml_get_error_code',
    'xml_error_string',
    'xml_get_current_line_number',
    'xml_get_current_column_number',
    'xml_get_current_byte_index',
    'xml_parser_free',
    'xml_parser_set_option',
    'xml_parser_get_option',
    'xmlwriter_open_uri',
    'xmlwriter_open_memory',
    'xmlwriter_set_indent',
    'xmlwriter_set_indent_string',
    'xmlwriter_start_comment',
    'xmlwriter_end_comment',
    'xmlwriter_start_attribute',
    'xmlwriter_end_attribute',
    'xmlwriter_write_attribute',
    'xmlwriter_start_attribute_ns',
    'xmlwriter_write_attribute_ns',
    'xmlwriter_start_element',
    'xmlwriter_end_element',
    'xmlwriter_full_end_element',
    'xmlwriter_start_element_ns',
    'xmlwriter_write_element',
    'xmlwriter_write_element_ns',
    'xmlwriter_start_pi',
    'xmlwriter_end_pi',
    'xmlwriter_write_pi',
    'xmlwriter_start_cdata',
    'xmlwriter_end_cdata',
    'xmlwriter_write_cdata',
    'xmlwriter_text',
    'xmlwriter_write_raw',
    'xmlwriter_start_document',
    'xmlwriter_end_document',
    'xmlwriter_write_comment',
    'xmlwriter_start_dtd',
    'xmlwriter_end_dtd',
    'xmlwriter_write_dtd',
    'xmlwriter_start_dtd_element',
    'xmlwriter_end_dtd_element',
    'xmlwriter_write_dtd_element',
    'xmlwriter_start_dtd_attlist',
    'xmlwriter_end_dtd_attlist',
    'xmlwriter_write_dtd_attlist',
    'xmlwriter_start_dtd_entity',
    'xmlwriter_end_dtd_entity',
    'xmlwriter_write_dtd_entity',
    'xmlwriter_output_memory',
    'xmlwriter_flush',
    'curl_close',
    'curl_copy_handle',
    'curl_errno',
    'curl_error',
    'curl_escape',
    'curl_unescape',
    'curl_multi_setopt',
    'curl_exec',
    'curl_file_create',
    'curl_getinfo',
    'curl_init',
    'curl_multi_add_handle',
    'curl_multi_close',
    'curl_multi_errno',
    'curl_multi_exec',
    'curl_multi_getcontent',
    'curl_multi_info_read',
    'curl_multi_init',
    'curl_multi_remove_handle',
    'curl_multi_select',
    'curl_multi_strerror',
    'curl_pause',
    'curl_reset',
    'curl_setopt_array',
    'curl_setopt',
    'curl_share_close',
    'curl_share_errno',
    'curl_share_init',
    'curl_share_setopt',
    'curl_share_strerror',
    'curl_strerror',
    'curl_version',
    'mb_language',
    'mb_internal_encoding',
    'mb_http_input',
    'mb_http_output',
    'mb_detect_order',
    'mb_substitute_character',
    'mb_preferred_mime_name',
    'mb_parse_str',
    'mb_output_handler',
    'mb_str_split',
    'mb_strlen',
    'mb_strpos',
    'mb_strrpos',
    'mb_stripos',
    'mb_strripos',
    'mb_strstr',
    'mb_strrchr',
    'mb_stristr',
    'mb_strrichr',
    'mb_substr_count',
    'mb_substr',
    'mb_strcut',
    'mb_strwidth',
    'mb_strimwidth',
    'mb_convert_encoding',
    'mb_convert_case',
    'mb_strtoupper',
    'mb_strtolower',
    'mb_detect_encoding',
    'mb_list_encodings',
    'mb_encoding_aliases',
    'mb_encode_mimeheader',
    'mb_decode_mimeheader',
    'mb_convert_kana',
    'mb_convert_variables',
    'mb_encode_numericentity',
    'mb_decode_numericentity',
    'mb_send_mail',
    'mb_get_info',
    'mb_check_encoding',
    'mb_scrub',
    'mb_ord',
    'mb_chr',
    'mb_regex_encoding',
    'mb_ereg',
    'mb_eregi',
    'mb_ereg_replace',
    'mb_eregi_replace',
    'mb_ereg_replace_callback',
    'mb_split',
    'mb_ereg_match',
    'mb_ereg_search',
    'mb_ereg_search_pos',
    'mb_ereg_search_regs',
    'mb_ereg_search_init',
    'mb_ereg_search_getregs',
    'mb_ereg_search_getpos',
    'mb_ereg_search_setpos',
    'mb_regex_set_options',
    'openssl_x509_export_to_file',
    'openssl_x509_export',
    'openssl_x509_fingerprint',
    'openssl_x509_check_private_key',
    'openssl_x509_verify',
    'openssl_x509_parse',
    'openssl_x509_checkpurpose',
    'openssl_x509_read',
    'openssl_x509_free',
    'openssl_pkcs12_export_to_file',
    'openssl_pkcs12_export',
    'openssl_pkcs12_read',
    'openssl_csr_export_to_file',
    'openssl_csr_export',
    'openssl_csr_sign',
    'openssl_csr_new',
    'openssl_csr_get_subject',
    'openssl_csr_get_public_key',
    'openssl_pkey_new',
    'openssl_pkey_export_to_file',
    'openssl_pkey_export',
    'openssl_pkey_get_public',
    'openssl_get_publickey',
    'openssl_pkey_free',
    'openssl_free_key',
    'openssl_pkey_get_private',
    'openssl_get_privatekey',
    'openssl_pkey_get_details',
    'openssl_pbkdf2',
    'openssl_pkcs7_verify',
    'openssl_pkcs7_encrypt',
    'openssl_pkcs7_sign',
    'openssl_pkcs7_decrypt',
    'openssl_pkcs7_read',
    'openssl_cms_verify',
    'openssl_cms_encrypt',
    'openssl_cms_sign',
    'openssl_cms_decrypt',
    'openssl_cms_read',
    'openssl_private_encrypt',
    'openssl_private_decrypt',
    'openssl_public_encrypt',
    'openssl_public_decrypt',
    'openssl_error_string',
    'openssl_sign',
    'openssl_verify',
    'openssl_seal',
    'openssl_open',
    'openssl_get_md_methods',
    'openssl_get_cipher_methods',
    'openssl_get_curve_names',
    'openssl_digest',
    'openssl_encrypt',
    'openssl_decrypt',
    'openssl_cipher_iv_length',
    'openssl_dh_compute_key',
    'openssl_pkey_derive',
    'openssl_random_pseudo_bytes',
    'openssl_spki_new',
    'openssl_spki_verify',
    'openssl_spki_export',
    'openssl_spki_export_challenge',
    'openssl_get_cert_locations',
    'xdebug_break',
    'xdebug_call_class',
    'xdebug_call_file',
    'xdebug_call_function',
    'xdebug_call_line',
    'xdebug_code_coverage_started',
    'xdebug_connect_to_client',
    'xdebug_debug_zval',
    'xdebug_debug_zval_stdout',
    'xdebug_dump_superglobals',
    'xdebug_get_code_coverage',
    'xdebug_get_collected_errors',
    'xdebug_get_function_count',
    'xdebug_get_function_stack',
    'xdebug_get_gc_run_count',
    'xdebug_get_gc_total_collected_roots',
    'xdebug_get_gcstats_filename',
    'xdebug_get_headers',
    'xdebug_get_monitored_functions',
    'xdebug_get_profiler_filename',
    'xdebug_get_stack_depth',
    'xdebug_get_tracefile_name',
    'xdebug_info',
    'xdebug_is_debugger_active',
    'xdebug_memory_usage',
    'xdebug_notify',
    'xdebug_peak_memory_usage',
    'xdebug_print_function_stack',
    'xdebug_set_filter',
    'xdebug_start_code_coverage',
    'xdebug_start_error_collection',
    'xdebug_start_function_monitor',
    'xdebug_start_gcstats',
    'xdebug_start_trace',
    'xdebug_stop_code_coverage',
    'xdebug_stop_error_collection',
    'xdebug_stop_function_monitor',
    'xdebug_stop_gcstats',
    'xdebug_stop_trace',
    'xdebug_time_index',
    'xdebug_var_dump',
    'opcache_reset',
    'opcache_get_status',
    'opcache_compile_file',
    'opcache_invalidate',
    'opcache_get_configuration',
    'opcache_is_script_cached',
    'dl',
    'cli_set_process_title',
    'cli_get_process_title',
    'mysqli_real_escape_string',
    'mysql_real_escape_string',
);

$INTERNALCLASS = array(
    'stdClass',
    'InternalIterator',
    'Exception',
    'ErrorException',
    'Error',
    'CompileError',
    'ParseError',
    'TypeError',
    'ArgumentCountError',
    'ValueError',
    'ArithmeticError',
    'DivisionByZeroError',
    'UnhandledMatchError',
    'Closure',
    'Generator',
    'ClosedGeneratorException',
    'WeakReference',
    'WeakMap',
    'Attribute',
    'DateTime',
    'DateTimeImmutable',
    'DateTimeZone',
    'DateInterval',
    'DatePeriod',
    'HashContext',
    'JsonException',
    'LogicException',
    'BadFunctionCallException',
    'BadMethodCallException',
    'DomainException',
    'InvalidArgumentException',
    'LengthException',
    'OutOfRangeException',
    'RuntimeException',
    'OutOfBoundsException',
    'OverflowException',
    'RangeException',
    'UnderflowException',
    'UnexpectedValueException',
    'RecursiveIteratorIterator',
    'IteratorIterator',
    'FilterIterator',
    'RecursiveFilterIterator',
    'CallbackFilterIterator',
    'RecursiveCallbackFilterIterator',
    'ParentIterator',
    'LimitIterator',
    'CachingIterator',
    'RecursiveCachingIterator',
    'NoRewindIterator',
    'AppendIterator',
    'InfiniteIterator',
    'RegexIterator',
    'RecursiveRegexIterator',
    'EmptyIterator',
    'RecursiveTreeIterator',
    'ArrayObject',
    'ArrayIterator',
    'RecursiveArrayIterator',
    'SplFileInfo',
    'DirectoryIterator',
    'FilesystemIterator',
    'RecursiveDirectoryIterator',
    'GlobIterator',
    'SplFileObject',
    'SplTempFileObject',
    'SplDoublyLinkedList',
    'SplQueue',
    'SplStack',
    'SplHeap',
    'SplMinHeap',
    'SplMaxHeap',
    'SplPriorityQueue',
    'SplFixedArray',
    'SplObjectStorage',
    'MultipleIterator',
    'ReflectionException',
    'Reflection',
    'ReflectionFunctionAbstract',
    'ReflectionFunction',
    'ReflectionGenerator',
    'ReflectionParameter',
    'ReflectionType',
    'ReflectionNamedType',
    'ReflectionUnionType',
    'ReflectionMethod',
    'ReflectionClass',
    'ReflectionObject',
    'ReflectionProperty',
    'ReflectionClassConstant',
    'ReflectionExtension',
    'ReflectionZendExtension',
    'ReflectionReference',
    'ReflectionAttribute',
    'SessionHandler',
    '__PHP_Incomplete_Class',
    'php_user_filter',
    'Directory',
    'AssertionError',
    'PhpToken',
    'ZipArchive',
    'InflateContext',
    'DeflateContext',
    'LibXMLError',
    'DOMException',
    'DOMImplementation',
    'DOMNode',
    'DOMNameSpaceNode',
    'DOMDocumentFragment',
    'DOMDocument',
    'DOMNodeList',
    'DOMNamedNodeMap',
    'DOMCharacterData',
    'DOMAttr',
    'DOMElement',
    'DOMText',
    'DOMComment',
    'DOMCdataSection',
    'DOMDocumentType',
    'DOMNotation',
    'DOMEntity',
    'DOMEntityReference',
    'DOMProcessingInstruction',
    'DOMXPath',
    'PDOException',
    'PDO',
    'PDOStatement',
    'PDORow',
    'OpenSSLCertificate',
    'OpenSSLCertificateSigningRequest',
    'OpenSSLAsymmetricKey',
    'SimpleXMLElement',
    'SimpleXMLIterator',
    'XMLParser',
    'XMLReader',
    'XMLWriter',
    'CurlHandle',
    'CurlMultiHandle',
    'CurlShareHandle',
    'CURLFile',
    'PharException',
    'Phar',
    'PharData',
    'PharFileInfo'
);